# Generated by Selenium IDE (corrigido e melhorado)
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTestquiz():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 10)  # Espera padrão de até 10 segundos
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testquiz(self):
        self.driver.get("http://localhost:5174/")
        self.driver.set_window_size(1295, 695)

        # Aguardando e clicando nos botões e opções em sequência
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button:nth-child(1)"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".option:nth-child(2) > p"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button:nth-child(6)"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".option:nth-child(2) > p"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".option:nth-child(4) > p"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".option:nth-child(3)"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button:nth-child(4)"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".option:nth-child(1) > p"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
        self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button"))).click()
